version: '3'
services:
  api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/var/www/html
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
      - ./frontend:/var/www/html