# Generated by Django 4.0 on 2022-02-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voices',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='voice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='praise.voices'),
        ),
        migrations.AlterField(
            model_name='voices',
            name='title',
            field=models.CharField(help_text='曲名', max_length=30),
        ),
    ]
